CREATE SCHEMA IF NOT EXISTS web_chat;

DROP DOMAIN IF EXISTS gender CASCADE;
CREATE DOMAIN gender CHAR(1) CHECK ( VALUE IN ('M', 'F', 'U'));

CREATE TABLE IF NOT EXISTS person (
  id         INTEGER PRIMARY KEY,
  name       TEXT NOT NULL,
  birth_date DATE NOT NULL,
  gender     GENDER DEFAULT 'U'
);

COMMIT;