DROP OWNED BY web_chat;
DROP USER IF EXISTS web_chat;
CREATE ROLE web_chat WITH
  LOGIN
  NOCREATEDB
  NOCREATEROLE
  ENCRYPTED PASSWORD 'password';
DROP DATABASE IF EXISTS web_chat;
CREATE DATABASE web_chat WITH OWNER = web_chat ENCODING = 'UTF8';
COMMIT;